build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Tamilarasi - Developer"
    email: "tamilarasi.srinivasan@outlook.com"
  onCallSupport:
    - (91) 89407-73705
    - (555) 523-1345